from typing import Dict, Any
from mapek.knowledge import KnowledgeBase

class Plan:
    """Plans workflows (pipeline adaptations) based on symptoms generated by Analyze."""
    
    def __init__(self):
        pass

    def create_workflow(self, symptoms: Dict[str, Any], kb: KnowledgeBase):
        """If adaptation is needed, updates the current pipeline in knowledge base."""
        if symptoms.get("adaptation_needed"):
            new_pipeline = symptoms["new_pipeline"]
            kb.current_pipeline = new_pipeline
            # Adaptation performed
        else:
            # Plan execute need not be invoked to change pipeline, it remains the same
            pass
            
        return kb.current_pipeline
